# Generated by Django 3.2.7 on 2021-10-28 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sign_in', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
