# Generated by Django 3.2.7 on 2021-10-14 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_auto_20211011_1326'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='employee',
        ),
    ]
