# Generated by Django 3.2.7 on 2021-10-15 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_alter_product_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='Product',
        ),
    ]
