# Generated by Django 3.2.7 on 2021-10-22 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0006_about'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='about',
            table='About',
        ),
    ]
