# Generated by Django 3.2.7 on 2021-10-28 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_auto_20211023_1023'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
