# Generated by Django 3.2.7 on 2022-01-01 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0010_useraddressbook'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='useraddressbook',
            table='UserAddressBook',
        ),
    ]
