# Generated by Django 3.2.7 on 2022-01-01 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0011_alter_useraddressbook_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAddressBook',
        ),
    ]
